FROM jaegertracing/jaeger-collector:1.18
FROM alpine
COPY --from=0 /go/bin/collector-linux /go/bin/collector-linux
ENV SPAN_STORAGE_TYPE grpc-plugin
ENV GRPC_STORAGE_PLUGIN_BINARY "/go/bin/jaeger-logzio"
COPY ./jaeger-logzio /go/bin/
ENTRYPOINT /go/bin/collector-linux
