region: "us"
apiToken: "api-token"
accountToken: "sapmle-token"
customListenerUrl: "http://example.com"
customQueueDir: "/tmp"
inMemoryQueue: true
compress: false
inMemoryCapacity: 500
logCountLimit: 500
drainInterval: 5