name: Test Go

on:
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Test
      run: |
        cd store
        pwd
        go test -v -race ./... -covermode=atomic -coverprofile=coverage.out
